/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./../src/components/AppButton.vue')['default']
    AppHeader: typeof import('./../src/components/AppHeader.vue')['default']
    AppSelect: typeof import('./../src/components/AppSelect.vue')['default']
    BackButton: typeof import('./../src/components/BackButton.vue')['default']
    BlankLayout: typeof import('./../src/layouts/BlankLayout.vue')['default']
    CardFooter: typeof import('./../src/components/CardFooter.vue')['default']
    Carousel: typeof import('./../src/components/Carousel.vue')['default']
    DashboardActions: typeof import('./../src/views/dashboard/components/DashboardActions.vue')['default']
    DashboardText: typeof import('./../src/views/dashboard/components/DashboardText.vue')['default']
    DefaultLayout: typeof import('./../src/layouts/DefaultLayout.vue')['default']
    Divider: typeof import('./../src/components/Divider.vue')['default']
    Dropdown: typeof import('./../src/components/Dropdown.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconArrowBig: typeof import('~icons/icon/arrow-big')['default']
    IconArrowSmall: typeof import('~icons/icon/arrow-small')['default']
    LazyImage: typeof import('./../src/components/LazyImage.vue')['default']
    NavList: typeof import('./../src/components/NavList.vue')['default']
    NavSidebar: typeof import('./../src/components/NavSidebar.vue')['default']
    PhoneWarningDialog: typeof import('~icons/ph/one-warning-dialog')['default']
    ProfileDropdown: typeof import('./../src/components/ProfileDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouterViewAnimated: typeof import('./../src/components/RouterViewAnimated.vue')['default']
    Tooltip: typeof import('./../src/components/Tooltip.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
